# Generated by Django 4.2.3 on 2023-07-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_items_global_shared"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="real_path",
        ),
        migrations.RemoveField(
            model_name="items",
            name="size",
        ),
        migrations.AddField(
            model_name="items",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
